{{- if .Values.hyperlane.validator.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "validator.fullname" . }}
  labels:
    {{- include "agent-common.labels" . | nindent 4 }}
data:
{{- range $index, $config := .Values.hyperlane.validator.configs }}
  validator-{{ $index }}.env: |
    {{- include "agent-common.config-env-vars" (dict "config" (get $config "chainSigner") "format" "dot_env" "key_name_prefix" (printf "CHAINS_%s_SIGNER_" ($config.originChainName | upper))) | nindent 4 }}
    {{- include "agent-common.config-env-vars" (dict "config" (omit $config "chainSigner") "format" "dot_env") | nindent 4 }}
{{- end }}
{{- end }}
